Add label test
negi-douf/pokemon_wordle pull request #12
Opened 2022-07-01 22:07 UTC by inahym196

Gameクラスのlabelテストを追加した

2022-07-01 22:10 UTC, inahym196 commented
> #9 に関連してGameクラスのlabelテストを追加した

conflictは#8のmerge後に対応します

2022-07-03 05:33 UTC, inahym196 commented
ちょっと別件になりますがpoetry環境で実行するコマンドは`poetry run python pokemon_wordle pokemon_list.csv`になりますので図とREADMEの更新が必要そうですよ。

2022-07-12 13:12 UTC, negi-douf requested changes

2022-07-12 13:12 UTC, negi-douf commented on poetry.lock
> +<<<<<<< HEAD
conflictの形跡が残っているので消したいです

2022-07-12 13:12 UTC, negi-douf commented on poetry.lock
> +=======
conflictの形跡が残っているので消したいです

2022-07-12 13:12 UTC, negi-douf commented on poetry.lock
> +>>>>>>> origin/add-test
conflictの形跡が残っているので消したいです

2022-07-13 12:58 UTC, negi-douf commented
ありがとうございます 👍 
READMEの修正はマージ後にやります

2022-07-13 12:58 UTC, merged