restructure
negi-douf/pokemon_wordle pull request #8
Opened 2022-05-29 14:45 UTC by inahym196

2022-06-04 05:05 UTC, negi-douf requested changes
直したいところ... 👀 
- 統一感をもたせる
- round

答えを出しておきたい... 🤔 
- いくつかの命名

2022-06-04 05:05 UTC, negi-douf commented on pokemon_wordle.py
> +    def print_winner(self):
returnの型ヒントを書くなら統一したいかな〜

2022-06-04 05:05 UTC, negi-douf commented on pokemon_wordle.py
> +        count_moji: dict[str, int] = {}
適切な名前はなんだろう...
char_count？count_per_char？count_each_char？countは複数形？
何かいいのないかな〜

2022-06-04 05:05 UTC, negi-douf commented on pokemon_wordle.py
> +    def move_next_turn(self) -> None:
`move_to_next_turn()` というのはどうだろう？？

2022-06-04 05:05 UTC, negi-douf commented on pokemon_wordle.py
> +        if type_02 == '':
クォートを統一したい 👀

2022-06-04 05:05 UTC, negi-douf commented on pokemon_wordle.py
>  def arg_parser() -> Namespace:
`parse_args()` のほうが好みだけど、どっちがいいんだろう...

2022-06-04 05:05 UTC, negi-douf commented on pokemon_wordle.py
> +        self.round = 0
ここが 0だと最初に正解したときに「0手目で正解！」になっちゃうね
1のほうがいいかも

2022-06-04 05:05 UTC, negi-douf commented on pokemon_wordle.py
> +class SoloPlayGame(Game):
パスカルケースに統一されてよかった！ 👍

2022-07-01 17:55 UTC, inahym196 commented on pokemon_wordle.py
> +    def print_winner(self):
Noneつけました！

2022-07-01 17:57 UTC, inahym196 commented on pokemon_wordle.py
> +        count_moji: dict[str, int] = {}
`num_of_appearances_of_chars`としました。そもそもこの処理自体変えたいけどね。。

2022-07-01 17:57 UTC, inahym196 commented on pokemon_wordle.py
> +    def move_next_turn(self) -> None:
変えました〜！

2022-07-01 17:57 UTC, inahym196 commented on pokemon_wordle.py
> +        if type_02 == '':
全部`""`にしました

2022-07-01 17:57 UTC, inahym196 commented on pokemon_wordle.py
>  def arg_parser() -> Namespace:
そうします！

2022-07-01 17:57 UTC, inahym196 commented on pokemon_wordle.py
> +        self.round = 0
thx!

2022-07-02 01:49 UTC, negi-douf requested changes

2022-07-02 01:49 UTC, negi-douf commented on pokemon_wordle.py
> +    def __init__(self, answer_pokemon: Pokemon) -> None:
pep8によるとクラスの関数を定義する前には 1行ぶんの空行を入れるとよいそうです

2022-07-02 01:49 UTC, negi-douf commented on pokemon_wordle.py
> +    def responce_of_this_turn(self) -> str:
`response` の typo？

2022-07-02 01:49 UTC, negi-douf commented on pokemon_wordle.py
> +        for responce_char, answer_char in zip(responce, answer):
この実装だと「緑のラベルが優先される」という仕様から外れてしまってますね...悲しい...
![スクリーンショット 2022-07-02 10 36 34](https://user-images.githubusercontent.com/18657640/176982142-b0ef7022-7830-4d1f-b272-e4c03fc85e0e.png)

2022-07-02 01:49 UTC, negi-douf commented on pokemon_wordle.py
> +        answer_counter = Counter(answer)
なるほど、Counterを使えば楽に実装できるのか 💡

2022-07-02 03:26 UTC, inahym196 commented on pokemon_wordle.py
> +    def __init__(self, answer_pokemon: Pokemon) -> None:
その記述を探しましたが、関数・クラス`間`には改行を入れる冪とはありますが先頭については記述がなく、autopep8による補完も行われませんでした。プロジェクトで規定すればいい(規定しないのもアリ)ですが、どちらかに統一しますか？
https://pep8-ja.readthedocs.io/ja/latest/#section-8

2022-07-02 15:46 UTC, inahym196 commented
Gameクラスを見直すと、このクラスの役割はターン・ユーザ管理とsystemcommandの管理に見えてきた。
colorlabelの処理はcolorlabelクラスに任せた。

2022-07-02 15:53 UTC, inahym196 commented
こうなるとクラスと変数の流れが分かりやすくなった気がする
- mainはargsを処理し、pokemon_wordleを呼び出す
- gameはPokemon(answer)とresponseを処理し、システムコマンドを呼び出す。内部でターン・ユーザ管理もする
- colorlabelは内部にlabelをもち、feedback_strを返す

2022-07-03 01:20 UTC, negi-douf commented on pokemon_wordle.py
> +    def __init__(self, answer_pokemon: Pokemon) -> None:
たしかに...どこかで見た気がしただけもしれません。ごめんなさい！
改行なしのままで大丈夫です 👌

2022-07-03 04:00 UTC, negi-douf requested changes

2022-07-03 04:00 UTC, negi-douf commented on pokemon_wordle.py
> +            if response_char in need_to_label_list:
65行目、この判定だとすでに GREENが入っていても YELLOWで上書きされちゃうケースがありますね
こうすると解決できそうです
```suggestion
            if labels[index] != Color.GREEN and response_char in need_to_label_list:
```

2022-07-03 04:04 UTC, negi-douf commented on pokemon_wordle.py
> +            if response_char in need_to_label_list:
これみたいに
- 同じ文字が複数入っている
- 片方は GREENでもう片方は YELLOW
というときに発生しそうな予感
![スクリーンショット 2022-07-03 13 02 45](https://user-images.githubusercontent.com/18657640/177024086-63153647-0167-4543-a076-4ddf9393edc2.png)

2022-07-03 04:48 UTC, inahym196 commented on pokemon_wordle.py
> +            if response_char in need_to_label_list:
ほんとだ、ありがとうございますm(__)m

2022-07-03 04:58 UTC, negi-douf approved these changes

2022-07-03 04:59 UTC, merged